### PR TITLE
Fix-issue #2

### PR DESCRIPTION
**Pull request by yashksaini-coder**
Hi @programmer-rahul 
Hope you are doing well, This PR is raised to Fix the issue #2 
Changes Made:-
image
<br>
Add Simple Hover effect to the NavLinks while maintaining smooth scroll behaviour, so it does not affect your header configuration.

- [X] Add Violet color change when hovered upon by user
- [x] Add Text enhancement when hovered upon by user

### CODE REVIEW

**Comment by programmer-rahul** [comment]
Hi @yashksaini-coder ,

Thank you for adding the hover effect to the navigation links. The effect looks good overall. However, I have a few suggestions:

**Text Size on Hover**: You increased the text size to text-2xl on hover. This change makes the header grow in size, which might not be desirable. It would be better to maintain a consistent header size.

**Color Consistency**: You've used a violet color for the hover effect. To maintain consistency across the website, please use the main color of the website, which is similar to violet. This will ensure a cohesive look and feel.

**CSS for Hover Effect**: Here is an example of CSS you can use for the hover effect:

```css
.nav-link {
  position: relative;
}
.nav-link::after {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  margin: auto;
  width: 0%;
  content: ".";
  color: transparent;
  background: #aaa;
  height: 1px;
  transition: all 0.5s;
}
.nav-link:hover:after {
  width: 100%;
}
.nav-link:hover {
  color: rgba(var(--main));
}

```

Thank you for your hard work and contributions!

Best regards,
Rahul

**Comment by yashksaini-coder** [comment]
Hi @programmer-rahul, I came up with the best way to add your desired Hover effect on the Nav link. I only know enough NEXT Js to implement these changes into the repo.

Changes I made:- 
- [X] Add a `NavBar.module.css` file
- [X] Set the color hover effects originally from your set vars of globals css.
- [X] Add a small line effect in Hover of Nav Link.

Again I do hope that these changes are more suitable to your choice. And if you still feels that the changes are not to your taste then I understand and apologize for holding this for quite a time.

PS: I really loved your portfolio. 

image
<br>
image

**Comment by programmer-rahul** [comment]
Hi @yashksaini-coder,

Thank you for implementing the hover effect on the Nav links. The changes look great!

Changes Reviewed:

- Added NavBar.module.css file
- Set color hover effects using the global CSS variables
- Added a small line effect on hover for the Nav links

I appreciate your effort and the attention to detail. The updates are well-aligned with what I had in mind. No need to apologize for the time taken; the quality of your work is worth it.

P.S. Thank you for the kind words about my portfolio!

**Comment by yashksaini-coder** [comment]
@programmer-rahul , I just want to thank you for giving me a second chance. Not many people point out the mistake or say what they want. When saw your message thought that this PR is not going to be merged. But still you did. Thanks for giving me a chance. 

Really appreciate it.

**Comment by programmer-rahul** [comment]
@yashksaini-coder,

You're very welcome! I believe in constructive feedback and growth, and I'm glad we could work together to improve the project. Your effort and responsiveness made a significant difference, and I appreciate your dedication to making this PR successful.

By the way, I checked out your GitHub profile readme—it's quite impressive!

**Comment by yashksaini-coder** [comment]
Thanks @programmer-rahul

**Pull request merged**
